-- V4: force byte-wise ("C") collation on every fractional-ordering key column.
--
-- WHY THIS EXISTS (do not revert):
-- Ordering keys are base62 fractional-index strings (e.g. "V", "l", "t") generated by
-- app.cairn.api.tasks.ordering. Their correctness depends on the database comparing them
-- BYTE-WISE (ASCII), because that is the ordering the generator assumes when it computes a
-- key "between" two neighbours.
--
-- Under a linguistic collation (en_US.utf8, most ICU locales) PostgreSQL instead compares
-- them like words: case is a tie-breaker rather than a primary weight, so 'l' < 't' < 'V'
-- instead of 'V' < 'l' < 't'. Rows then come back in the wrong order and every list, board,
-- section and portfolio ordering silently rotates.
--
-- This bit us for real: the local dev cluster is C.UTF-8 (byte-wise, tests passed) while the
-- CI postgres:16 container initialises with en_US.utf8 (linguistic, four integration tests
-- failed). Pinning COLLATE "C" on the columns makes ordering identical on every deployment
-- regardless of the cluster/database locale, and rebuilds the supporting indexes with the
-- same collation so index scans stay consistent with ORDER BY.
--
-- Any future column that stores a fractional-ordering key MUST also declare COLLATE "C";
-- SortKeyCollationIntegrationTest asserts this for every *_sort_key column.

alter table sections           alter column sort_key         type varchar(255) collate "C";
alter table tasks              alter column sort_key         type varchar(255) collate "C";
alter table tasks              alter column subtask_sort_key type varchar(255) collate "C";
alter table portfolios         alter column sort_key         type varchar(255) collate "C";
alter table portfolio_projects alter column sort_key         type varchar(255) collate "C";
